// Generated by CoffeeScript 1.7.1
(function(console) {
  return console.save = function(data, filename) {
    var a, blob, e;
    if (filename == null) {
      filename = "console.json";
    }
    if (!data) {
      console.error("Console.save: No data!");
      return;
    }
    if (typeof data === "object") {
      data = JSON.stringify(data, void 0, 4);
    }
    blob = new Blob([data], {
      type: "text/json"
    });
    e = document.createEvent("MouseEvents");
    a = document.createElement("a");
    a.download = filename;
    a.href = window.URL.createObjectURL(blob);
    a.dataset.downloadurl = ["text/json", a.download, a.href].join(":");
    e.initMouseEvent("click", true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    return a.dispatchEvent(e);
  };
})(console);
