// Generated by CoffeeScript 1.7.1
(function() {
  Plotter.DataSorter = (function() {
    var ajaxPromise, duckFilter, fullSet, getDataset, subSet;
    fullSet = void 0;
    subSet = void 0;
    ajaxPromise = void 0;
    getDataset = function() {
      return $.getJSON("data/clean-dataset.08-12.min.json", function(json) {
        fullSet = new Collection(json);
        return $.pub("dataset:complete", [fullSet]);
      });
    };
    duckFilter = function(ppArr, seasonArr) {
      var filterObj, prop;
      if (!fullSet) {
        throw new Error("Sorry, dataset not loaded.");
        return;
      }
      prop = "";
      if (ppArr[0].split(" ").length > 1) {
        prop = "name";
      } else {
        prop = "position";
      }
      filterObj = [
        {
          prop: prop,
          vals: ppArr
        }, {
          prop: "season",
          vals: positionArr
        }
      ];
      return subSet = fullSet.multiWhereArray(filterObj, true);
    };
    $(function() {
      return getDataset();
    });
    return {
      duckFilter: duckFilter,
      fullSet: function() {
        return fullSet;
      },
      subSet: function() {
        return subSet;
      }
    };
  })();

}).call(this);
