// Generated by CoffeeScript 1.7.1
(function(App) {
  var dotHolder, infoBar, render, renderInfo;
  infoBar = $(".chart-info-bar");
  dotHolder = $("#dot-holder");
  render = function(d) {
    return "<span class='player-name'>" + d.name + "</span>\n<span class='player-season'>" + d.season + "</span>\n<span class='player-position'>" + d.position + "</span>";
  };
  renderInfo = function(dot) {
    var markup, playerData;
    dot = $(dot);
    playerData = {
      name: dot.data("player-name"),
      position: dot.data("player-position"),
      season: dot.data("player-season")
    };
    markup = render(playerData);
    return infoBar.empty().html(markup);
  };
  $("body").on("mouseenter", ".scatterplot-point", function(evt) {
    $(this).data("real-r", $(this).data("r"));
    console.log($(this).data("real-r"));
    return renderInfo(this);
  });
  return $("body").on("mouseleave", ".scatterplot-point", function(evt) {
    return infoBar.empty();
  });
})(window.Plotter);
