// Generated by CoffeeScript 1.7.1
(function() {
  (function(App) {
    var hub;
    hub = $({});
    App.on = function() {
      return hub.on.apply(hub, arguments);
    };
    App.off = function() {
      return hub.off.apply(hub, arguments);
    };
    App.trigger = function() {
      return hub.trigger.apply(hub, arguments);
    };
    return $(function() {
      return $.getJSON("data/clean-dataset.08-13.min.json", function(json) {
        return App.trigger("dataSetLoaded", [json]);
      });
    });
  })(window.Plotter);

}).call(this);
