// Generated by CoffeeScript 1.7.1
(function(App) {
  var hub;
  hub = new EventEmitter();
  App.on = function() {
    return hub.on.apply(hub, arguments);
  };
  App.off = function() {
    return hub.off.apply(hub, arguments);
  };
  App.emitEvent = function() {
    return hub.emitEvent.apply(hub, arguments);
  };
  App.trigger = function() {
    return hub.trigger.apply(hub, arguments);
  };
  return $(function() {
    return $.getJSON("data/data-redux.json", function(json) {
      return App.trigger("dataSetLoaded", [json]);
    });
  });
})(window.Plotter);
