// Generated by CoffeeScript 1.7.1
(function() {
  (function(App) {
    var CONSTANTS, last, numericalSort;
    CONSTANTS = {
      r: {
        min: 2,
        max: 10
      },
      c: {
        min: -.15,
        max: .15
      }
    };
    numericalSort = function(a, b) {
      return a - b;
    };
    last = function(arr) {
      return arr[arr.length - 1];
    };
    return App.ScaleMaker = function(dataSet, vars) {
      var cVals, rVals, scales, xVals, yVals;
      xVals = dataSet.pluck(vars.xVar).sort(numericalSort);
      yVals = dataSet.pluck(vars.yVar).sort(numericalSort);
      rVals = dataSet.pluck(vars.rVar).sort(numericalSort);
      cVals = dataSet.pluci(vars.cVar).sort(numericalSort);
      return scales = (function() {
        return {
          x: d3.scale.linear().domain([xVals[0], last(xVals)]),
          y: d3.scale.linear().domain([yVals[0], last(yVals)]),
          r: d3.scale.linear().domain([rVals[0], last(rVals)]).range([CONSTANTS.r.min, CONSTANTS.r.max]),
          c: d3.scale.linear().domain([cVals[0], last(cVals)]).range([CONSTANTS.c.min, CONSTANTS.c.max])
        };
      })();
    };
  })(window.Plotter);

}).call(this);
