// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $("#ppSwitchPosition")[0].checked = true;
    $("#gsSwitchSeason")[0].checked = true;
    $("#check-rb")[0].checked = true;
    $("#check-wr")[0].checked = true;
    $("#x-var-select").find("option[value='FantPt']")[0].selected = true;
    $("#y-var-select").find("option[value='PosRank']")[0].selected = true;
    $("#size-var-select").find("option[value='TotalTD']");
    return $("#shade-var-select").find("option[value='ScrimYds']");
  });

}).call(this);
